web_dl_crawltrack_crawler:
    resource: "@WebDLCrawltrackBundle/Resources/config/routing/crawler.yml"
    prefix:   /crawler

webdl_crawltrack_homepage:
    path:     /
    defaults: { _controller: WebDLCrawltrackBundle:Default:index }

webdl_crawltrack_crawls_crawler_date:
    path:     /visits/{crawler_id}/{crawl_date}/{page}
    defaults: { _controller: WebDLCrawltrackBundle:Visits:showByDateCrawler, page: 1 }

webdl_crawltrack_crawler_details:
    path:     /crawler/{crawler_id}
    defaults: { _controller: WebDLCrawltrackBundle:Crawler:view }