<?php

namespace WebDL\CrawltrackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CrawlerDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlerDataRepository extends EntityRepository
{
}
