<?php

namespace WebDL\CrawltrackBundle\Entity;

/**
 * CrawlerUADataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlerUADataRepository extends \Doctrine\ORM\EntityRepository
{
}
