<?php

namespace WebDL\CrawltrackBundle\Entity;

/**
 * CrawlerDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlerDataRepository extends \Doctrine\ORM\EntityRepository
{
}
