<?php

namespace WebDL\CrawltrackBundle\Entity;

/**
 * CrawlerIPDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlerIPDataRepository extends \Doctrine\ORM\EntityRepository
{
}
