parameters:
    webdl_crawltrack.db_table_prefix: crwlt_

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WebDL\CrawltrackBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{Entity,Migrations,Tests}'

    WebDL\CrawltrackBundle\Subscriber\TablePrefixSubscriber:
        arguments:
            - '%webdl_crawltrack.db_table_prefix%'
        tags:
            - { name: doctrine.event_subscriber }

    WebDL\CrawltrackBundle\EventListener\CrawltrackRequestListener:
        arguments:
            $blacklistedIps: '%webdl_crawltrack.ip_blacklist%'
        tags:
            - { name: kernel.event_listener, event: kernel.request }
