crawler:
    path:     /
    defaults: { _controller: "WebDLCrawltrackBundle:Crawler:index" }

crawler_show:
    path:     /{id}/show
    defaults: { _controller: "WebDLCrawltrackBundle:Crawler:show" }

crawler_new:
    path:     /new
    defaults: { _controller: "WebDLCrawltrackBundle:Crawler:new" }

crawler_create:
    path:     /create
    defaults: { _controller: "WebDLCrawltrackBundle:Crawler:create" }
    methods:  POST

crawler_edit:
    path:     /{id}/edit
    defaults: { _controller: "WebDLCrawltrackBundle:Crawler:edit" }

crawler_update:
    path:     /{id}/update
    defaults: { _controller: "WebDLCrawltrackBundle:Crawler:update" }
    methods:  [POST, PUT]

crawler_toggle:
    path:     /{id}/toggle
    defaults: { _controller: "WebDLCrawltrackBundle:Crawler:toggle" }

crawler_delete:
    path:     /{id}/delete
    defaults: { _controller: "WebDLCrawltrackBundle:Crawler:delete" }
    methods:  [POST, DELETE]
